/**
 * SubRadar Desktop — 1-Click Legal Cancellation Notice Generator
 * 
 * Formats official legal cancellation & termination letters complying with:
 * - 6502 Sayılı Tüketicinin Korunması Hakkında Kanun (Mesafeli Sözleşmeler Yönetmeliği)
 * - EU Consumer Rights Directive (2011/83/EU) & GDPR Art. 17 Data Erasure
 */

function generateLegalNotice({
  serviceName,
  planName = '',
  accountEmail = '',
  accountId = '',
  price = '',
  currency = 'TRY',
  renewalDate = '',
  userName = 'Abone / Müşteri',
  language = 'tr'
}) {
  const dateStr = new Date().toLocaleDateString(language === 'tr' ? 'tr-TR' : 'en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  if (language === 'tr') {
    return `RESMİ ABONELİK FESİH VE OTOMATİK YENİLEME İPTAL BİLDİRİMİ

Tarih: ${dateStr}
Kime: ${serviceName} Müşteri Hizmetleri / Hukuk & Faturalandırma Departmanı
Konu: Abonelik İptali, Otomatik Ödeme Talimatının Kaldırılması ve Fesih İhbarı

Sayın Yetkili,

Şahsıma ait aşağıda detayları belirtilen kullanıcı hesabı kapsamında yürütülmekte olan "${serviceName}${planName ? ' (' + planName + ')' : ''}" aboneliğimin derhal ve en geç bir sonraki yenileme tarihi olan ${renewalDate || 'fatura kesim tarihi'} itibarıyla sona erdirilmesini talep ediyorum.

ABONELİK VE HESAP BİLGİLERİ:
• Hizmet Sağlayıcı: ${serviceName}
• Paket / Lisans: ${planName || 'Standart Abonelik'}
• Kayıtlı E-Posta: ${accountEmail || '[E-Posta Adresiniz]'}
• Müşteri / Abonelik No: ${accountId || '[Opsiyonel Müşteri Numarası]'}
• Tutar: ${price} ${currency}

YASAL GEREKÇE VE DAYANAK:
6502 sayılı Tüketicinin Korunması Hakkında Kanun ve Mesafeli Sözleşmeler Yönetmeliği’nin ilgili hükümleri uyarınca;
1. Tarafıma ait kayıtlı kredi kartı, banka kartı veya sanal kart üzerinden herhangi bir yeni periyodik çekim veya otomatik provizyon yapılmasını ONAYLAMIYORUM.
2. Bu bildirim tarihi itibarıyla yenilenen ödeme talimatının sistemlerinizden kaldırılmasını,
3. 6698 sayılı Kişisel Verilerin Korunması Kanunu (KVKK) uyarınca, yasal saklama zorunluluğu bulunmayan ödeme bilgilerimin ve ticari elektronik ileti izinlerimin derhal silinmesini/anonimleştirilmesini talep ederim.

Aboneliğimin herhangi bir cezai şart veya cayma bedeli yansıtılmaksızın iptal edildiğine ve bir sonraki dönem için herhangi bir faturalandırma yapılmayacağına dair yazılı teyidin kayıtlı e-posta adresime ivedilikle iletilmesini arz ve talep ederim.

Saygılarımla,

Adı Soyadı: ${userName}
Tarih: ${dateStr}
Oluşturan: SubRadar Masaüstü Yerel Kasa (Sürüm 1.4.2)
`;
  }

  // English (International / GDPR)
  return `OFFICIAL NOTICE OF SUBSCRIPTION CANCELLATION & REVOCATION OF RECURRING BILLING

Date: ${dateStr}
To: ${serviceName} Customer Support & Billing Department
Subject: Immediate Cancellation of Subscription and Revocation of Direct Debit Authorization

To Whom It May Concern,

I am writing to formally request the immediate cancellation of my subscription for "${serviceName}${planName ? ' (' + planName + ')' : ''}", effective immediately or prior to the upcoming billing cycle scheduled for ${renewalDate || 'the next billing date'}.

ACCOUNT DETAILS:
• Service Provider: ${serviceName}
• Subscription Plan: ${planName || 'Standard Subscription'}
• Account Email: ${accountEmail || '[Your Account Email]'}
• Customer / Account ID: ${accountId || '[Optional Account ID]'}
• Recurring Cost: ${price} ${currency}

LEGAL TERMS & REVOCATION:
Pursuant to applicable consumer protection legislation and the EU Consumer Rights Directive:
1. I hereby REVOKE all authorizations for recurring charges or automated debits against my credit/debit card on file.
2. Please ensure no further automated renewals occur from this date forward.
3. In accordance with GDPR (Article 17 - Right to Erasure), I also request the deletion of non-essential billing profiles and marketing consent once the final account reconciliation is complete.

Please provide immediate written confirmation of this cancellation to my email address on record.

Sincerely,

Name: ${userName}
Date: ${dateStr}
Generated by: SubRadar Desktop Vault (v1.4.2)
`;
}

module.exports = {
  generateLegalNotice
};
